version: "3"
services:
  app:
    build:
      args:
        user: javi
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: javi98/laravel-client-juegos-api:1.0.0
    container_name: laravel-client-juegos-api-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - /var/www/vendor
      - ./docker-config/php/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini

  nginx:
    image: nginx:alpine
    container_name: laravel-client-juegos-api-web
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./docker-config/nginx:/etc/nginx/conf.d

networks:
  laravel-api-client:
    driver: bridge
